<a href="https://colab.research.google.com/github/IonatanPerezColab/CursoML/blob/main/Semana1/Curso_ML_Semana_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cosas generales

## Glosario

- Supervisado: Que hay data de ejemplos con rta.
- Clasificador: Que el output es categorico. Es caso de supervidado.
- Regresion: Que el output es continuo. Es caso de supervisado
- No supervisado: No hay etiquetas previas en los datos, hay que separar en funcion de ubicación en espacio de fases, clustering
- Training set: Datos que se usan para entrenar. Conjunto de m valores input x con su valor de salida y. m pares (x,y) donde x puede pertenecer a $R^n$ y lo mismo y.  
- Parametros del modelo: Valores $\theta_i$ del modelo h(x)
- Funcion costo cuadratica: $\sum_1^m \frac{1}{2m}\cdot(h_\theta(x_i) - y_i)^2 $
- Gradiente descendiente: algoritmo de optimización que usa el gradiente de la función costos respecto de los parametros $\theta$ para moverse en el espacio de parametros y minimizar la funcion costo. 

## Convenciones de nombres del curso
- x: input del modelo supervisado
- y: output del modelo supervisado
- m: Cantidad de entradas del dataset. 
- h: modelo que tiene por input a un x y como salida a un valor y: h(x) = y
- $h_\theta$ : modelo que depende de los parametros $\theta_i$
- $J(h,\theta)$: funcion costo. $\frac{1}{2} \sum_i (\hat y_i - y_i)^2$


## Ideas
- Cuadrados minimos: minizar la expresion $(h_\theta(x) - y)^2$
- Funcion costo cuadratica: Se elije con norma dos porque suele funcionar bien con los modelos pero es una elección y puede haber otras.
- Metodo de gradiente descendiente busca minimos locales. Es inestable frente a condiciones iniciales de prueba.

# Notas sobre el curso

## Semana 1

### Parte 1 : Intro
- Trabajan con Octave, voy a tratar de buscar equivalentes en python porque el curso es viejo y probablemente todo lo que no estaba en python en ese momento ya este implementado en librerias. De paso practico buscar cosas en python.

### Parte 2 : Funcion costo

Arranca con ejemplo de regresion. Modelo lineal $h(x_i) = \theta_0 + \theta_1 \cdot x_i = y_i$

### Parte 3 : Algoritmo de gradiente

Usan una notacion horrible para las igualdades y las asignaciones. 
El algortimo gradiente descendiente hace: $\vec \theta_i - \alpha \nabla J(\theta_i)$

Resulta que $J(\theta)$ definida como distancias cuadratica es convexa y solo tiene un minimo lo que soluciona el problema de la convergencia a minimos locales. 

### Parte 4, algebra lineal

Notaciones usuales de algebra, vectores, matrices, notacion row/column. Ojo que hay que tener cuidado porque en algebra el primer elemento es el 1, en gral en codigo tipo python es el 0, pero en el curso usan octave! Estuve busando y R usa el 1 tambien parece. 

Usando notacion matricial, un modelo lineal de la forma $h(x)= y_i = \theta_0 + \theta_1 \cdot x_i + \theta_2 \cdot x^2_i ...$ se puede escribir como $Y = X \cdot \Theta $ donde X es de la forma $$ X = \begin{bmatrix}
x_1^0 & x_1^1 & x_1^2 & ...\\
x_2^0 & x_2^1 & x_2^2 & ...\\
... & ... & ... & ...
\end{bmatrix} $$

De la misma forma si queremos evaluar en simultaneo muchos posibles parametros de $\Theta$ podemos armar una matriz de la forma

$$ \Theta = \begin{bmatrix}
\theta_0^{h_1} & \theta_0^{h_2} & ...\\
\theta_1^{h_1} & \theta_1^{h_2} & ...\\
\theta_2^{h_1} & \theta_2^{h_2} & ...\\
... & ... & ...
\end{bmatrix} $$

### Parte 5, algebra lineal

Sigue hablando de matrices, propiedades, inversas y transpuestas. No se bien para que presenta este tema pero viene bien de repaso.

In [ ]:

# Codigo equivalente a los ejemplos del la semana 1.4.1 (algebra lineal)

import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
v = np.array([1,2,3])
m,n = A.shape
A_23 = A[1,2] # No encontre que numpy acepte la notiacion empezando con 1
print (A_23)

# Codigo equivalente a los ejemplos de la semana 1.4.2

A = np.array([[1,2,4],
              [5,3,2]])

B = np.array([[1,2,3],
              [1,1,1]])
s = 5
print (A+B)
print (A-B)
print (A*s)
print (A/s)
print ('Lo que sigue se comporta diferente a los previsto con la notacion matematica usual que debería dar error')
print (A+s)

# Codigo equivalente a los ejemplos de la semana 1.4.3

print ("Inicio de ejemplos de la parte 1.4.3")
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
v = np.array([1,1,1])
print ("matriz A")
print (A)
print ("vector v")
print (v)
print ("Si ponemos A*v no da lo que uno espera.")
print (A*v)
print ("En cambio funciona si usamos np.dot(A,v)")
print (np.dot(A,v))
print ('O bien podemos usar A.dot(v)')
print (A.dot(v))

# Codigo equivalente a los ejemplos de la semana 1.4.5

print ("\n Ejemplos 1.4.5 \n")
A = np.random.randint(10,size = (2,2))
B = np.random.randint(10,size = (2,2))
I = np.identity(2, dtype=int)
print ("I * A:")
print (I.dot(A))
print ("A * I:")
print (A.dot(I))
print ("B * A:")
print (B.dot(A))
print ("A * B:")
print (A.dot(B))

print ("\n Ejemplos 1.4.6 \n")
A = np.array([[1,2,0],
              [0,5,6],
              [7,0,9]])
print (np.transpose(A))
print (np.linalg.inv(A))
print (np.linalg.inv(A).dot(A))

6
[[2 4 7]
 [6 4 3]]
[[0 0 1]
 [4 2 1]]
[[ 5 10 20]
 [25 15 10]]
[[0.2 0.4 0.8]
 [1.  0.6 0.4]]
Lo que sigue se comporta diferente a los previsto con la notacion matematica usual que debería dar error
[[ 6  7  9]
 [10  8  7]]
Inicio de ejemplos de la parte 1.4.3
matriz A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
vector v
[1 1 1]
Si ponemos A*v no da lo que uno espera.
[[1 2 3]
 [4 5 6]
 [7 8 9]]
En cambio funciona si usamos np.dot(A,v)
[ 6 15 24]
O bien podemos usar A.dot(v)
[ 6 15 24]

 Ejemplos 1.4.5 

I * A:
[[3 5]
 [7 3]]
A * I:
[[3 5]
 [7 3]]
B * A:
[[27 45]
 [12 20]]
A * B:
[[47  0]
 [75  0]]

 Ejemplos 1.4.6 

[[1 0 7]
 [2 5 0]
 [0 6 9]]
[[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]
[[ 1.00000000e+00 -8.32667268e-17  5.55111512e-17]
 [-2.77555756e-17  1.00000000e+00 -2.77555756e-17]
 [-3.46944695e-17  2.77555756e-17  1.00000000e+00]]
